version: 0.6.2.{build}
platform: x64
init:
- cmd: "ECHO %MSYS% \nSET PATH=%MSYS%;%MSYS%\\bin;%PATH%"

environment:
  '%MSYS%': C:\msys64

build_script:
- cmd: >-
    mkdir _build32

    cd _build32

    cmake -G "Visual Studio 14 2015" ..

    cd ..


    mkdir _build64

    cd _build64

    cmake -G "Visual Studio 14 2015 Win64" ..

    cd ..


    cmake --build _build32 --config Release

    cmake --build _build64 --config Release


    7z a libdiscid-%APPVEYOR_BUILD_VERSION%-win32.zip %APPVEYOR_BUILD_FOLDER%\_build32\Release\*.*

    appveyor PushArtifact libdiscid-%APPVEYOR_BUILD_VERSION%-win32.zip

    7z a libdiscid-%APPVEYOR_BUILD_VERSION%-win64.zip %APPVEYOR_BUILD_FOLDER%\_build64\Release\*.*

    appveyor PushArtifact libdiscid-%APPVEYOR_BUILD_VERSION%-win64.zip
